using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class AnimalHungerUI : MonoBehaviour
{

    public Slider hungerSlider;
    public int amountToBeFed;

    private int currentFedAmount = 0;
    // Start is called before the first frame update
    void Start()
    {
        hungerSlider.maxValue = amountToBeFed;
        hungerSlider.value = 0;
        hungerSlider.fillRect.gameObject.SetActive(false);

    }

    // Update is called once per frame
    void Update()
    {

        
    }

    public void FeedAnimal(int amount)
    {
        currentFedAmount += amount;
        hungerSlider.fillRect.gameObject.SetActive(true);
        hungerSlider.value = currentFedAmount;
        if (currentFedAmount >= amountToBeFed)
        {
            GameManager.Instance.AddScores(amountToBeFed);
            Destroy(gameObject, 0.1f);
        }
    }

}
